fix/nextjs-warning
Nexters/daily-phrase-web pull request #32
Opened 2024-01-31 15:16 UTC by bepyan

## 🤔 해결하려는 문제

nextjs 에서 던지는 경고를 해소했소!
- hydration warning
- list map key

## 📃 공유할 변경사항

## 📷 스크린샷

## 📚 참고

2024-01-31 16:32 UTC, kingyong9169 requested changes

2024-01-31 16:32 UTC, kingyong9169 commented on apps/back-office/src/app/page.tsx
> +  const data = getPhraseItemListMocks(totalRows);
data를 여기에 두면 useQuery를 쓸거고 useQuery를 쓰면 use client를 써야 할거야! ManageServiceTemplate에서 data를 호출하려는 의도는 다음과 같아.
1. page 에서는 query string 혹은 params 로직 처리(현재는 그렇지 않아!), 레이아웃만 담당
2. Suspense와 ErrorBoundary로 감싸서 예외 처리를 하기 위함.
3. ManageServiceTemplate 이름 자체가 특정 도메인에 속하기 때문에 특정 도메인에 맞는 UI로 구성되어 있고 데이터 호출도 여기서 담당.
4. 테이블 row를 클릭했을 때, 글귀 생성 및 수정 드로워 UI 렌더링(테이블, 드로워가 렌더링은 페이지 담당)

과 같아! 만약 데이터 호출을 페이지에서 하려고 했다면 ManageServiceTemplate을 따로 만들지 않았을거야!

의견 있으면 알려줘~

2024-01-31 17:05 UTC, kingyong9169 commented
혹시 hydration 워닝이 뜨는 이유가 뭐였어?!?!?!

2024-02-01 04:35 UTC, bepyan commented
> 혹시 hydration 워닝이 뜨는 이유가 뭐였어?!?!?!

SSR 결과물이 CSR 결과물이 달라서 뜨는 오류인데..
지금은 page에서 템플릿에 정적 데이터를 넘겨주고, 추후 ManageServiceTemplate에서 useQuery를 쓰게 될 때 리팩토링해주면 될 것 같아!

<img width="963" alt="image" src="https://github.com/Nexters/daily-phrase-web/assets/65283190/9aa01732-d5a4-45de-8c30-481a0eeae36e">

2024-02-01 15:04 UTC, merged